# Generated by Django 3.2.6 on 2021-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usreinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(default='pinkal', max_length=200),
            preserve_default=False,
        ),
    ]
