# Generated by Django 3.2.6 on 2021-08-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usreinfo', '0002_userdata_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='category',
            field=models.CharField(choices=[('LS', 'liscense'), ('ID', 'Identity'), ('ED', 'education'), ('CR,', 'certificate'), ('OT', 'others')], default=('OT', 'others'), max_length=200),
        ),
    ]
